---
- hosts: all
  become: true
  pre_tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - nfs-server
    - kvm-legacy
    - vagrant
    - vagrant-libvirt
